### ISSUE TITLE
plugin feature "on_should_nickname_pokemon" is useless on French Emerald

### ISSUE THREAD

**Issue by vbkantoine** [40Cakes/pokebot-gen3#500]
The actual issue seems to be that the function `handle_nickname_caught_pokemon` is never called by `handle_battle` in `modules.battle_handler`.

I tried the simple following plugin :
```python
from modules.plugin_interface import BotPlugin

class TestPlugin(BotPlugin):

    def on_should_nickname_pokemon(self, pokemon: "Pokemon") :
        if pokemon.species.name=="Lotad"  :
            return "Q"
        return None
```
my custom catch filters admit to catch any Lotad. I tested Spin bot mode or level griding, when the Lotad is met, it is caught but nicknaming is skipped (the bot hit 'B').

It appears while playing French Pokemon Emerald, below is `metadata.yml` :
```
version: 1
rom:
  file_name: Pokemon - Version Emeraude (France).gba
  game_code: BPE
  revision: 0
  language: F
```
